[project]
name = "image_warped_events"
version = "0.1"
dependencies = [
  "torch>=2.2.1",
  "torchvision>=0.18.1",
  "numpy>=1.22.4",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
